version: '3'
services:
  app:
    container_name: bumblebot
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        UID: $UID
        GID: $GID
    volumes:
      - '.:/data'
    env_file:
      - .env
    ports:
      - $PORT:9042
    user: $UID:$GID
    command: ["yarn", "run", "serve"]
